{
  config,
  pkgs,
  lib,
  ...
}:

{
  environment.systemPackages = with pkgs; [
    abootimg
    amdgpu_top
    android-tools
    appstream
    arch-install-scripts
    bibata-cursors
    binwalk
    brscan4
    brscan5
    btrfs-progs
    bubblemail
    bzip2
    ccache
    curl
    czkawka
    ddcutil
    discord-krisp
    distrobox
    docker-buildx
    docker-compose
    dog
    eza
    ffmpeg
    ffmpegthumbnailer
    file
    flat-remix-gnome
    flat-remix-gtk
    flatpak-xdg-utils
    freerdp
    fuse
    fuse3
    fwupd
    gimp
    gnome-tweaks
    gnome.gvfs
    gotop
    gparted
    gst_all_1.gstreamer
    gst_all_1.gst-vaapi
    gst_all_1.gst-libav
    gst_all_1.gst-plugins-bad
    gst_all_1.gst-plugins-good
    gst_all_1.gst-plugins-ugly
    gst_all_1.gst-plugins-base
    gvfs
    gzip
    htop
    i2c-tools
    iftop
    inkscape
    iotop
    jq
    killall
    kooha
    krita
    lact
    libnotify
    libreoffice
    linux-firmware
    lm_sensors
    lrzip
    lsof
    lz4
    lzip
    lzop
    mangohud
    mesa-demos
    mission-center
    ncdu
    nil
    nixfmt-rfc-style
    noisetorch
    ntfs3g
    nvtopPackages.amd
    openrgb-with-all-plugins
    papirus-icon-theme
    pbzip2
    pigz
    plymouth
    poppler-utils
    prismlauncher-unwrapped
    protonup-qt
    radeontop
    rquickshare
    scrcpy
    screen
    seafile-client
    smartmontools
    starship
    sushi
    swtpm
    telegram-desktop
    testdisk
    thunderbird
    tidal-hifi
    tldr
    tree
    unrar
    unzip
    ventoy-full-gtk
    vesktop
    vkbasalt
    vlc
    vscode-fhs
    wev
    weylus
    wget
    which
    wine
    wireshark
    xfce.tumbler
    xz
    yt-dlp
    zenmonitor
    zip
    zram-generator
    zsh-autosuggestions
    zsh-completions
    zsh-history-substring-search
    zsh-syntax-highlighting
    zstd
    zulu8
    zulu17
    zulu23
  ];

  fonts = {
    packages = with pkgs; [
      fira-code
      font-awesome
      nerd-fonts.fira-code
      nerd-fonts.fira-mono
      nerd-fonts.symbols-only
      nerd-fonts.ubuntu-mono
      noto-fonts
      noto-fonts-cjk-sans
      noto-fonts-color-emoji
      ubuntu-classic
    ];
  };
}
