{
  config,
  pkgs,
  lib,
  ...
}:

{
  environment.gnome.excludePackages = with pkgs; [
    decibels
    epiphany
    geary
    gnome-connections
    gnome-contacts
    gnome-logs
    gnome-maps
    gnome-music
    gnome-software
    gnome-system-monitor
    snapshot
    totem
    yelp
  ];

  environment.systemPackages = lib.flatten [
    (with pkgs.gnomeExtensions; [
      # thanatophobia
      alphabetical-app-grid
      appindicator
      blur-my-shell
      control-monitor-brightness-and-volume-with-ddcutil
      bubblemail
      color-picker
      dash-to-dock
      favorites-to-applications-grid
      middle-click-to-close-in-overview
      undecorate
      user-themes
    ])
    (with pkgs; [
      abootimg
      amdgpu_top
      android-tools
      appstream
      arch-install-scripts
      bibata-cursors
      binwalk
      brscan4
      brscan5
      btrfs-progs
      bubblemail
      bzip2
      ccache
      curl
      czkawka
      ddcutil
      discord-krisp
      distrobox
      docker-compose
      dog
      eza
      ffmpeg
      ffmpegthumbnailer
      file
      flat-remix-gnome
      flat-remix-gtk
      flatpak-xdg-utils
      freecad
      freerdp
      fuse
      fuse3
      fwupd
      gimp
      gnome-tweaks
      gnome.gvfs
      gotop
      gparted
      gvfs
      htop
      i2c-tools
      iftop
      inkscape
      iotop
      killall
      krita
      kooha
      lact
      libnotify
      libreoffice
      linux-firmware
      lm_sensors
      lsof
      mangohud
      mesa-demos
      mission-center
      ncdu
      nil
      nixfmt-rfc-style
      noisetorch
      ntfs3g
      nvtopPackages.amd
      openrgb-with-all-plugins
      papirus-icon-theme
      plymouth
      poppler-utils
      prismlauncher-unwrapped
      protonup-qt
      radeontop
      rquickshare
      scrcpy
      screen
      seafile-client
      smartmontools
      starship
      sushi
      swtpm
      telegram-desktop
      testdisk
      thunderbird
      tidal-hifi
      tldr
      tree
      unrar
      unzip
      ventoy-full-gtk
      vesktop
      vkbasalt
      vlc
      vscode-fhs
      wireshark
      wev
      weylus
      wget
      which
      wine
      xfce.tumbler
      yt-dlp
      zenmonitor
      zip
      zram-generator
      zsh-autosuggestions
      zsh-completions
      zsh-history-substring-search
      zsh-syntax-highlighting
      zulu8
      zulu17
      zulu23
    ])
  ];

  fonts = {
    packages = with pkgs; [
      fira-code
      font-awesome
      nerd-fonts.fira-code
      nerd-fonts.fira-mono
      nerd-fonts.symbols-only
      nerd-fonts.ubuntu-mono
      noto-fonts
      noto-fonts-cjk-sans
      noto-fonts-color-emoji
      ubuntu-classic
    ];
  };
}
