# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "uas" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/688ed267-cec9-400a-9226-32b0538eaecd";
      fsType = "btrfs";
      options = [
        "subvol=@nix"
        "ssd"
        "space_cache=v2"
        "noatime"
        "compress=zstd"
       ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/688ed267-cec9-400a-9226-32b0538eaecd";
      fsType = "btrfs";
      options = [
        "subvol=@home"
        "ssd"
        "space_cache=v2"
        "noatime"
        "compress=zstd"
       ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/688ed267-cec9-400a-9226-32b0538eaecd";
      fsType = "btrfs";
      options = [
        "subvol=@nix_nix"
        "ssd"
        "space_cache=v2"
        "noatime"
        "compress=zstd"
       ];

    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/688ed267-cec9-400a-9226-32b0538eaecd";
      fsType = "btrfs";
      options = [
        "subvol=@nix_var"
        "ssd"
        "space_cache=v2"
        "noatime"
        "compress=zstd"
       ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3DB5-50DE";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/media/data" =
    { device = "/dev/disk/by-uuid/4c0c8b24-6fca-49c1-8e34-e00e240576e3";
      fsType = "btrfs";
      options = [ "subvol=Data" ];
    };

  fileSystems."/media/games" =
    { device = "/dev/disk/by-uuid/4c0c8b24-6fca-49c1-8e34-e00e240576e3";
      fsType = "btrfs";
      options = [ "subvol=Games" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = true;
}
