{
  pkgs,
  lib,
  ...
}: {
  home.packages = with pkgs;
    [
      alejandra
      binwalk
      bubblemail
      czkawka-full
      element-desktop
      gemini-cli
      gitu
      just
      libreoffice-fresh
      nil
      nix-output-monitor
      nix-your-shell
      rquickshare
      telegram-desktop
      testdisk
      tldr
      trash-cli
      treefmt
      vesktop
      vlc
      yt-dlp
    ]
    ++ lib.optionals pkgs.stdenv.hostPlatform.isx86_64 [
      cisco-packet-tracer_9
      discord
      jetbrains.clion
      protonup-qt
      scrcpy
      tidal-hifi
      gimp
      inkscape
    ];
}
