{
  config,
  pkgs,
  lib,
  czkawka-master,
  solaar-master,
  fet,
  ...
}:
{
  nixpkgs = {
    config = {
      allowUnfree = true;
      permittedInsecurePackages = [
        "ventoy-gtk3-1.1.10"
        "cisco-packet-tracer_9"
      ];
    };
    overlays = [
      (final: prev: {
        nautilus = prev.nautilus.overrideAttrs (nprev: {
          buildInputs =
            nprev.buildInputs
            ++ (with pkgs.gst_all_1; [
              gst-plugins-bad
              gst-plugins-base
              gst-plugins-good
              gst-plugins-ugly
            ]);
        });
      })
    ];
  };

  environment.systemPackages = with pkgs; [
    abootimg
    alejandra
    android-tools
    anki
    appstream
    aspell
    aspellDicts.cs
    aspellDicts.en
    aspellDicts.es
    attic-client
    bibata-cursors
    binwalk
    brscan4
    brscan5
    btrfs-progs
    bubblemail
    bzip2
    cisco-packet-tracer_9
    curl
    ddcutil
    discord
    distrobox
    docker-buildx
    docker-compose
    element-desktop
    eza
    fet.packages.${pkgs.stdenv.hostPlatform.system}.default
    ffmpeg-full
    ffmpegthumbnailer
    file
    file-roller
    flat-remix-gnome
    flat-remix-gtk
    flatpak-xdg-utils
    freerdp
    fuse
    fuse3
    fwupd
    gemini-cli
    gimp
    gnome-tweaks
    gnome.gvfs
    gotop
    gparted
    gphoto2
    gst_all_1.gst-libav
    gst_all_1.gst-plugins-bad
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-good
    gst_all_1.gst-plugins-ugly
    gst_all_1.gst-vaapi
    gst_all_1.gstreamer
    gvfs
    gzip
    htop
    i2c-tools
    iftop
    inkscape
    iotop
    jetbrains.clion
    jq
    just
    killall
    libgsf
    libnotify
    libreoffice-fresh
    libsForQt5.qtstyleplugins
    linux-firmware
    lm_sensors
    logitech-udev-rules
    lrzip
    lsof
    lz4
    lzip
    lzop
    mangohud
    mesa-demos
    mission-center
    ncdu
    networkmanager-openconnect
    nil
    nix-output-monitor
    nix-your-shell
    nixfmt
    nixfmt-tree
    ntfs3g
    nufraw-thumbnailer
    obsidian
    papirus-icon-theme
    pbzip2
    pciutils
    pigz
    plymouth
    poppler-utils
    prismlauncher-unwrapped
    protonup-qt
    rquickshare
    saber
    scrcpy
    screen
    seafile-client
    smartmontools
    solaar
    sushi
    telegram-desktop
    testdisk
    thunderbird
    tidal-hifi
    tldr
    trash-cli
    tree
    tumbler
    unrar
    unzip
    usbutils
    ventoy-full-gtk
    vesktop
    vkbasalt
    vlc
    (vscode.fhsWithPackages (
      ps: with ps; [
        python3
        zlib
        gcc
        gnumake
      ]
    ))
    webp-pixbuf-loader
    wev
    wget
    which
    wineWow64Packages.waylandFull
    wireshark
    xz
    yt-dlp
    zip
    zram-generator
    zstd
    zulu
    zulu17
    zulu8
  ];

  fonts = {
    packages = with pkgs; [
      fira-code
      font-awesome
      nerd-fonts.fira-code
      nerd-fonts.fira-mono
      nerd-fonts.symbols-only
      nerd-fonts.ubuntu-mono
      noto-fonts
      noto-fonts-cjk-sans
      noto-fonts-color-emoji
      ubuntu-classic
    ];
  };
}
