# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "uas"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/02dad628-066d-4fba-ada7-bfdfbc2e4ca3";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "ssd"
      "space_cache=v2"
      "noatime"
      "compress=zstd:8"
      "autodefrag"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/02dad628-066d-4fba-ada7-bfdfbc2e4ca3";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "ssd"
      "space_cache=v2"
      "noatime"
      "compress=zstd:7"
      "autodefrag"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/02dad628-066d-4fba-ada7-bfdfbc2e4ca3";
    fsType = "btrfs";
    options = [
      "subvol=@nix_nix"
      "ssd"
      "space_cache=v2"
      "noatime"
      "compress=zstd:10"
      "autodefrag"
    ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/02dad628-066d-4fba-ada7-bfdfbc2e4ca3";
    fsType = "btrfs";
    options = [
      "subvol=@nix_var"
      "ssd"
      "space_cache=v2"
      "noatime"
      "compress=zstd:10"
      "autodefrag"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C871-B294";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
