# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "uas"
        "sd_mod"
      ];
      kernelModules = [ ];
    };

    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];

    kernelParams = [
      "snd_hda_intel.power_save=1"
      "mem_sleep_default=deep"
      "i915.enable_guc=3"
      "i915.enable_fbc=1"
    ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7b31f189-b34a-4cf0-95c5-bbcd6830159e";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "ssd"
      "space_cache=v2"
      "noatime"
      "compress=zstd:8"
      "autodefrag"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/7b31f189-b34a-4cf0-95c5-bbcd6830159e";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "ssd"
      "space_cache=v2"
      "noatime"
      "compress=zstd:7"
      "autodefrag"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/7b31f189-b34a-4cf0-95c5-bbcd6830159e";
    fsType = "btrfs";
    options = [
      "subvol=@nix_nix"
      "ssd"
      "space_cache=v2"
      "noatime"
      "compress=zstd:10"
      "autodefrag"
    ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/7b31f189-b34a-4cf0-95c5-bbcd6830159e";
    fsType = "btrfs";
    options = [
      "subvol=@nix_var"
      "ssd"
      "space_cache=v2"
      "noatime"
      "compress=zstd:10"
      "autodefrag"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/477C-4D52";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/bea07563-dc23-415b-b12f-ba53138bd492";
      priority = 0;
      options = [
        "defaults"
      ];

    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
